uploads = []
generated = []

[[outputs]]
id = "vSRVKU3sS9bDUIuTsQba-"
uri = "file://Unemployment_Intelligence_Platform_Project_Report.docx"
type = "word_document"
title = "UIP Project Report (Word Document)"
